# Generated by Django 3.2.7 on 2021-12-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
    ]
