# Generated by Django 3.2.7 on 2021-12-26 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211226_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
