# Generated by Django 3.2.7 on 2021-12-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211228_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
    ]
