# Generated by Django 3.2.7 on 2021-12-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211228_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.TimeField(),
        ),
    ]
