# Generated by Django 3.2.7 on 2021-12-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_bus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
